### ISSUE TITLE
404 errors while trying to get data

### ISSUE THREAD

**Issue by MTDouglas** [GenomePathogenAnalysisService/read-it-and-keep#15]
Hello,

While attempting to build a singularity container the following error occurs:
```
 + cd /bioinf-tools
wget https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz
+ wget https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz
--2024-01-22 14:25:44--  `https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz`
Resolving [www.niehs.nih.gov](https://www.niehs.nih.gov/) (www.niehs.nih.gov)... 104.18.14.200, 104.18.15.200, 2606:4700::6812:fc8, ...
Connecting to [www.niehs.nih.gov](https://www.niehs.nih.gov/) (www.niehs.nih.gov)|104.18.14.200|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-22 14:25:44 ERROR 404: Not Found.
 
FATAL:   While performing build: while running engine: exit status 8
```
Additionally, attempting to pull the docker image also gives a 404 error as well.
`docker pull ghcr.io/genomepathogenanalysisservice/read-it-and-keep:latest`

Was wondering if anyone has tried installing it recently and gotten similar issues.

Thanks in advance!

**Comment by martinghunt** [comment]
Sorry, there's a typo in the urls (the github organisation got renamed at some point after the readitandkeep readme was written).

This should work:

```
docker pull ghcr.io/globalpathogenanalysisservice/read-it-and-keep:latest
```

For singularity build: will need to figure this one out. Seems like the ART code is no longer available, which is a pain. A workaround for now (if it works on your architecture) would be to donwload the singularity image file from release 0.3.0: https://github.com/GlobalPathogenAnalysisService/read-it-and-keep/releases/tag/v0.3.0

**Comment by MTDouglas** [comment]
I see, that change seemed to have fixed the initial construction of building the docker image but we got the subsequent error partway through the building process. 

`Successfully built pyfastaq
Installing collected packages: tomli, packaging, iniconfig, exceptiongroup, pluggy, pytest, pyfastaq
Successfully installed exceptiongroup-1.2.0 iniconfig-2.0.0 packaging-23.2 pluggy-1.3.0 pyfastaq-3.17.0 pytest-7.4.4 tomli-2.0.1

+ cd /bioinf-tools
wget https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz
+ wget https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz
--2024-01-22 15:53:03--  https://www.niehs.nih.gov/research/resources/assets/docs/artbinmountrainier2016.06.05linux64.tgz
Resolving [www.niehs.nih.gov](https://www.niehs.nih.gov/) (www.niehs.nih.gov)... 104.18.14.200, 104.18.15.200, 2606:4700::6812:fc8, ...
Connecting to [www.niehs.nih.gov](https://www.niehs.nih.gov/) (www.niehs.nih.gov)|104.18.14.200|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-22 15:53:03 ERROR 404: Not Found.

The command '/bin/sh -c $RIK_WF_DIR/.ci/install_dependencies.sh /bioinf-tools' returned a non-zero code: 8`

Seems like the docker image is trying pull this data from the NIH.gov links but is getting an invalid URL.

**Comment by martinghunt** [comment]
It should work now as long as you're using linux - those links have reappeared overnight. The linux builds ok, but there is still an unrelated problem with mac.

**Comment by MTDouglas** [comment]
We were able to get the docker image to build. Unfortunately, we're getting some issues trying to get readitandkeep to run.  Doing 
`docker run read-it-and-keep --ref_fasta /path/to/ref/MN908947.3.no_poly_A.fa --reads1 /path/to/fastq1.fastq.gz --reads2 /path/to/fastq2.fastq.gz -o outdir/
`
produces 
```
--ref_fasta: File does not exist: /path/to/ref/MN908947.3.no_poly_A.fa
Run with --help for more information.
Error parsing command line options or input file not found. Cannot continue.

```
We've checked to make sure that the file does in fact exist given the path.

Thoughts on why this might be happening?

**Comment by martinghunt** [comment]
Docker run can't see files on the host without mounting them. There's the `-v` option.

With two fastq files in my current working directory, this works:

```
docker run -v $PWD:/foo read-it-and-keep --ref_fasta /readItAndKeep/tests/MN908947.3.no_poly_A.fa --reads1 /foo/ERR6386185_1.fastq.gz --reads2 /foo/ERR6386185_2.fastq.gz --outprefix /foo/out
```

**Comment by MTDouglas** [comment]
Gotcha, that seemed to have enabled it to run. Thanks for all your help!
