### ISSUE TITLE
Make file unable to compile

### ISSUE THREAD

**Issue by MTDouglas** [GenomePathogenAnalysisService/read-it-and-keep#17]
Hello, 
We tried to run the tests and we got the following error
`
======================================================================================================= ERRORS ========================================================================================================
____________________________________________________________________________________________ ERROR collecting test_all.py _____________________________________________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/media/Bacteria/readitandkeep/read-it-and-keep-0.3.0/tests/test_all.py", line 59
E       reads = " ".join([f"--reads{i+1} " + f for i, f in enumerate(reads_files)])
E                                        ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================================== 1 error in 0.07 seconds ===============================================================================================
make: *** [Makefile:23: test] Error 2
`
We've got all the proper dependences installed so that shouldn't be an issue so was curious if anyone else has encountered this issue.

Thanks

**Comment by martinghunt** [comment]
The tests need Python 3 to run. That error is from Python 2.
