### ISSUE TITLE
Feature request: FASTQ header sanitisation

### ISSUE THREAD

**Issue by bede** [GenomePathogenAnalysisService/read-it-and-keep#3]
As discussed, it would be great to have an optional feature to strip out FASTQ headers, which could conceivably contain identifying information.

When activated, FASTQ headers could be replaced with enumerated numbers or similar, so that they remain unique. I'm unsure what is the best suffix is for paired Illumina headers, there seem to be multiple standards.

In practice, this would also remove large high entropy strings (guids etc) usually inserted by the instrument and so reduce compressed file size considerably.

Ideas for argument naming
- `--sanitise_headers`
- `--enumerate_names`

**Comment by bede** [comment]
A quick test suggests that using enumerated headers drops gzipped file size by just below 10% for Nanopore Midnight amplicons, and just over 10% for Illumina 150bp ARTIC V3 amplicons.

**Comment by martinghunt** [comment]
Can you please spec out exactly what you want the new headers to look like?
* 1, 2, 3, 4  ... ?
* prefix.1, prefix.2, prefix.3, ...?
* something else?

For Illumina pairs, adding `/1` / `/2` to the end of the new headers will be the right thing to do.

**Comment by bede** [comment]
Enumerating a uint32 as decimals in the header seems the most straightforward. I can't see how this could break anything, can you? @iqbal-lab? 

```
@1
ATATTCAGCT
+
3AAB3AACFA
@2
ATATTCAGCT
+
3AAB3AACFA
```

(Hexadecimal also fine, perhaps less likely to be confused with coordinates when peeking at bams etc. But I don't think it matters)

**Comment by bede** [comment]
I guess some people might like to specify a prefix, but I don't see a need

**Comment by martinghunt** [comment]
righto, I'll implement enumerating for now...

**Comment by bede** [comment]
Thanks!
