### ISSUE TITLE
[Question] How closely related should be the reference fasta

### ISSUE THREAD

**Issue by camilogarciabotero** [GenomePathogenAnalysisService/read-it-and-keep#8]
Hi all,

Thank you for working on `read-it-and-keep`. I was wondering what should be my reference genome to map the reads onto? Could it be a previous assemble from nontreated reads, or should it be a reference genome closer to my species that resides already in a database?

Thanks in advance.

**Comment by martinghunt** [comment]
We're expecting it to be used for SARS-CoV-2. For other species, you'd need to test it (eg reads from your assembly, and use a genome from genbank as the target). It depends on how variable the species is.

**Comment by camilogarciabotero** [comment]
Oh thanks
