### ISSUE TITLE
Reference Multifasta?

### ISSUE THREAD

**Issue by JamesZlosnik** [GenomePathogenAnalysisService/read-it-and-keep#9]
This looks like a great tool.   Can I just ask if I supply a multifasta as the reference fasta file does it use the full set of sequences in there to map against or just the first?  I've tried supplying this and it works with an output, but I just want to be sure how it is working.  If it uses all the sequences, this would be very useful for mapping against multiple strains of a virus.

**Comment by martinghunt** [comment]
Yes, that's right. It will use all of the sequences in the reference fasta, not just the first sequence.

**Comment by JamesZlosnik** [comment]
Fantastic - this is very useful.   Thank you very much for the super speedy reply.!
